import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
// import { Orbitron, Delius, Rubik_Moonrocks } from "next/font/google";

import "./globals.css";

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  display: "swap", // optional but recommended
  weight: ["400", "700"], // optional: specify weights you need
});

// const delius = Delius({
//   subsets: ["latin"],
//   variable: "--font-delius",
//   display: "swap", // optional but recommended
//   weight: ["400"], // optional: specify weights you need
// });

// const rubikMoonrocks = Rubik_Moonrocks({
//   subsets: ["latin"],
//   variable: "--font-rubik-moonrocks",
//   display: "swap", // optional but recommended
//   weight: ["400"], // optional: specify weights you need
// });

// This is title and description of page.
export const metadata: Metadata = {
  title: "SmellPanty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubikMoonrocks.className} antialiased flex items-center justify-center min-h-screen flex-col`}
      >
        <h1 className="text-2xl text-gray-700 hover:text-blue-600 transition-colors duration-300">
          🦧 Rendered from layout.tsx on all pages 🦧
        </h1>
        {children}
      </body>
    </html>
  );
}
